enhanced monitor, process commands
piwik/plugin-QueuedTracking pull request #261
Opened 2024-10-09 13:45 UTC by haristku

### Description:

[breaking down the previous PR to specific part](https://github.com/matomo-org/plugin-QueuedTracking/pull/259)

- enhanced monitor, process commands

2024-10-13 22:51 UTC, snake14 requested changes
The Process changes look good and work as expected :+1: 

When I tried testing the Monitor changes, the paging didn't appear to work. It would insert new lines above the window height and the visible portion of the window didn't change. It appeared to be appending the help text after some of the lines as well.

2024-10-14 06:05 UTC, haristku commented
@snake14
what OS are you using to run the Monitor command? do you use *nix terminal or windows PowerShell or CMD?

unfortunately, i'm not running matomo in a Windows environment, so i don't have a chance to see the "Monitor" output in a Windows console like PowerShell or CMD.. 

🙏 ✌️

2024-10-14 20:12 UTC, snake14 commented
> @snake14 what OS are you using to run the Monitor command? do you use *nix terminal or windows PowerShell or CMD?
> 
> unfortunately, i'm not running matomo in a Windows environment, so i don't have a chance to see the "Monitor" output in a Windows console like PowerShell or CMD..
> 
> 🙏 ✌️

@haristku I'm running Ubuntu 22.04 and using the stock terminal.

2024-10-15 12:57 UTC, haristku commented
> The Process changes look good and work as expected 👍
> 
> When I tried testing the Monitor changes, the paging didn't appear to work. It would insert new lines above the window height and the visible portion of the window didn't change. It appeared to be appending the help text after some of the lines as well.

what if you add 3 rows per page args: 

`php console queuedtracking:monitor -p 3` 

what's the result? is the paging working or still not?

2024-10-15 21:58 UTC, snake14 approved these changes
Thank you for the suggestion of changing the page size. That helped me test some variations. Although, I tested without setting a specific page size again and it worked correctly. I'm not sure what the issue was last time I tested. I'm approving the PR :+1:

2024-10-16 01:45 UTC, AltamashShaikh commented on Commands/Process.php
> +                $output->writeln("<comment>Taking a nap for {$napster} second(s) before re-run the process. <info>({$cTogo})</info> cyle(s) to go.</comment>");
```suggestion
                $output->writeln("<comment>Taking a nap for {$napster} second(s), before re-running the process. <info>({$cTogo})</info> cyle(s) to go.</comment>");
```

2024-10-16 02:24 UTC, AltamashShaikh approved these changes
Looks okay to me, left  1 comment.

2024-10-16 08:12 UTC, haristku commented
> Looks okay to me, left 1 comment.

`pcntl` usage removed. the consequence is blinking cursor on monitor command… coz cursor hide and show mechanism cannot be restored without pcntl sigterm.

@AltamashShaikh @snake14 , have you ever tried the monitor command in a Windows environment? 
i hope the output and functionality can be the same in all environments.

2024-10-17 22:39 UTC, snake14 commented
> > Looks okay to me, left 1 comment.
> 
> `pcntl` usage removed. the consequence is blinking cursor on monitor command… coz cursor hide and show mechanism cannot be restored without pcntl sigterm.
> 
> @AltamashShaikh @snake14 , have you ever tried the monitor command in a Windows environment? i hope the output and functionality can be the same in all environments.

@haristku Thank you for all of your effort. I think that the PR looks ready to merge. Sadly, I don't think we currently have a Windows environment to test with. @AltamashShaikh Do you think that we're alright to merge anyway?

2024-10-18 02:37 UTC, AltamashShaikh commented
@snake14 We can merge this and address the concern for windows if any

2024-10-18 02:37 UTC, merged

2024-10-21 06:33 UTC, haristku commented
> @haristku Thank you for all of your effort. I think that the PR looks ready to merge. Sadly, I don't think we currently have a Windows environment to test with. @AltamashShaikh Do you think that we're alright to merge anyway?

thanks for creating matomo and this plugin in the first place. 👍

btw, i forgot to remove these [2 lines](https://github.com/matomo-org/plugin-QueuedTracking/blob/832db07eceac66855ea9c74874bdc105a03f4ee8/Commands/Monitor.php#L40), my intention is to clear the screen, but it seems unnecessary, you can remove them.✌️

2024-10-21 06:49 UTC, AltamashShaikh commented
@haristku Did you mean [this](https://github.com/matomo-org/plugin-QueuedTracking/blob/832db07eceac66855ea9c74874bdc105a03f4ee8/Commands/Monitor.php#L40..L41) 2 lines ?

2024-10-21 06:54 UTC, haristku commented
> @haristku Did you mean [this](https://github.com/matomo-org/plugin-QueuedTracking/blob/832db07eceac66855ea9c74874bdc105a03f4ee8/Commands/Monitor.php#L40..L41) 2 lines ?

yes...

2024-10-21 07:34 UTC, haristku commented
and 1 more update, change this [line](https://github.com/matomo-org/plugin-QueuedTracking/blob/832db07eceac66855ea9c74874bdc105a03f4ee8/Commands/Monitor.php#L106) to this:

```php
$diffRps        = number_format(round($diffSumInQueue / (microtime(true) - $lastStatsTimer)));
```

✌️

2024-10-21 08:10 UTC, AltamashShaikh commented
@haristku All done and released v5.1.0 of the plugin.

2024-10-21 08:15 UTC, haristku commented
ty sir... 🫡