disable monitor interactive paging on windows
piwik/plugin-QueuedTracking pull request #271
Opened 2024-10-22 02:33 UTC by haristku

### Description:
disable monitor interactive paging on Windows environment #269 

this PR will cause the monitor feature to have different behaviour between Windows and Linux.
please advise, are these different conditions allowed or not? if not allowed, i will adjust the code to remove the interactive paging feature altogether.

---

- the new `-r` parameter replace the old `-p`
- while `-p` now used to jump to specific page

**for example (if we have 16 queue workers):**
-  `php console queuedtracking:monitor` will display 16 rows per page (only 1 page)
- `php console queuedtracking:monitor -r 3` will display 3 rows per page (6 pages total)
- `php console queuedtracking:monitor -r 3 -p 2`  will display 3 rows per page and jump to 2nd page
- `php console queuedtracking:monitor -r 3 -p 6`  will display 3 rows per page and jump to 6th page

`-r` and `-p` will work both on Windows or Linux, but only Linux has the ability to move pages interactively.

@AltamashShaikh @snake14 do you have any other suggestions?

2024-10-22 14:34 UTC, AltamashShaikh commented on Commands/Monitor.php
> +        if (str_starts_with(strtoupper(PHP_OS), 'WIN')) {
@haristku Can you simplify this function to
```suggestion
        return function_exists('readline_callback_handler_install');
```

2024-10-22 14:36 UTC, AltamashShaikh requested changes
@haristku Requested 1 change rest looks good to me :+1:

2024-10-22 15:25 UTC, haristku commented
done.. 👍 
ty.

2024-10-22 21:22 UTC, snake14 approved these changes
Looks good. I didn't find any issues in my testing. Nice work! :+1: 

I didn't see any validation for a page number higher than there are pages, but it simply returns the last page when I tried it. I think that works fine.

2024-10-23 01:28 UTC, AltamashShaikh approved these changes

2024-10-23 01:28 UTC, merged